services:
  db:
    image: cibotminhminhchan/baubau-db:latest
    container_name: db_node
    env_file:
      - .env.db
    volumes:
      - baubaupgSQL:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fwmc_bridge
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-baubau_user} -d ${POSTGRES_DB:-baubau_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: cibotminhminhchan/baubau-app:latest
    container_name: backend_node
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fwmc_bridge
    restart: unless-stopped

volumes:
  baubaupgSQL:
    name: baubaupgSQL
    driver: local

networks:
  fwmc_bridge: 
    name: fwmc_bridge
    driver: bridge

  