server {
        listen 80;
        server_name 100.109.86.39;

        root /var/www/status_page;
        index status.html;

        location / {
                try_files $uri $uri/ =404;
        }
}